export const ENV = {
  // Core
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // DB/Redis
  DATABASE_URL: 'DATABASE_URL',
  SHADOW_DATABASE_URL: 'SHADOW_DATABASE_URL',
  REDIS_URL: 'REDIS_URL',

  // Cookies / CORS
  CORS_ORIGIN: 'CORS_ORIGIN',
  COOKIE_SECRET: 'COOKIE_SECRET',
  SESSION_COOKIE_NAME: 'SESSION_COOKIE_NAME',
  CSRF_COOKIE_NAME: 'CSRF_COOKIE_NAME',
  CSRF_HEADER_NAME: 'CSRF_HEADER_NAME',
  SESSION_TTL_DAYS: 'SESSION_TTL_DAYS',
  COOKIE_SECURE: 'COOKIE_SECURE',
  COOKIE_SAMESITE: 'COOKIE_SAMESITE',
  COOKIE_DOMAIN: 'COOKIE_DOMAIN',
  COOKIE_PATH: 'COOKIE_PATH',

  // Rate limit
  RATE_LIMIT_TTL_SECONDS: 'RATE_LIMIT_TTL_SECONDS',
  RATE_LIMIT_LIMIT: 'RATE_LIMIT_LIMIT',
  AUTH_RATE_LIMIT_TTL_SECONDS: 'AUTH_RATE_LIMIT_TTL_SECONDS',
  AUTH_RATE_LIMIT_LIMIT: 'AUTH_RATE_LIMIT_LIMIT',

  // Lockout
  AUTH_LOCKOUT_WINDOW_SECONDS: 'AUTH_LOCKOUT_WINDOW_SECONDS',
  AUTH_LOCKOUT_MAX_FAILURES: 'AUTH_LOCKOUT_MAX_FAILURES',
  AUTH_LOCKOUT_TTL_SECONDS: 'AUTH_LOCKOUT_TTL_SECONDS',
} as const;
