export const ENV = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  DATABASE_URL: 'DATABASE_URL',

  CORS_ORIGIN: 'CORS_ORIGIN',

  // cookies / sessions
  COOKIE_SECRET: 'COOKIE_SECRET',
  SESSION_COOKIE_NAME: 'SESSION_COOKIE_NAME',
  CSRF_COOKIE_NAME: 'CSRF_COOKIE_NAME',
  CSRF_HEADER_NAME: 'CSRF_HEADER_NAME',
  SESSION_TTL_DAYS: 'SESSION_TTL_DAYS',

  COOKIE_SECURE: 'COOKIE_SECURE',
  COOKIE_SAMESITE: 'COOKIE_SAMESITE',
  COOKIE_DOMAIN: 'COOKIE_DOMAIN',
  COOKIE_PATH: 'COOKIE_PATH',

  // rate limit
  AUTH_RL_WINDOW_SEC: 'AUTH_RL_WINDOW_SEC',
  AUTH_RL_MAX: 'AUTH_RL_MAX',
} as const;
